# permissions for end users to view etcdclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: etcdcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eto
    app.kubernetes.io/part-of: eto
    app.kubernetes.io/managed-by: kustomize
  name: etcdcluster-viewer-role
rules:
- apiGroups:
  - etcd.yz775
  resources:
  - etcdclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcd.yz775
  resources:
  - etcdclusters/status
  verbs:
  - get
