---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - etcd.yz775
  resources:
  - etcdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.yz775
  resources:
  - etcdclusters/finalizers
  verbs:
  - update
- apiGroups:
  - etcd.yz775
  resources:
  - etcdclusters/status
  verbs:
  - get
  - patch
  - update
